fix: feature detection webforms project
aws/cta pull request #422
Opened 2021-11-09 05:40 UTC by saikiranakula-amzn

## Related issue

Closes: #ISSUE_NUMBER_HERE

## Description
* Describe the changes in this pull request

## Supplemental testing
Describe any testing done in addition to existing unit tests

## Additional context
Please provide any additional information related to this PR

---
*By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.*

2021-11-09 17:22 UTC, jonlouie requested changes

2021-11-09 17:22 UTC, jonlouie commented on tst/CTA.FeatureDetection.Tests/Fixtures/TestProjectsSetupFixture.cs
> +        public static string WebFormsSolutionPath => @"D:\TestRepos\TestProjects\net472\FeatureDetection\WebForms\ASP.NET-WebForms.sln";
Can we replace the string literal with `Path.Combine(...)` like other solution paths?

e.g. `WebFormsSolutionPath => Path.Combine(_targetDir, _webFormsDir, WebFormsSolutionName);`

2021-11-09 17:22 UTC, jonlouie commented on tst/CTA.FeatureDetection.Tests/Fixtures/TestProjectsSetupFixture.cs
> +        public static string WebFormsProjectPath => @"D:\TestRepos\TestProjects\net472\FeatureDetection\WebForms\ASP.NET-WebForms\ASP.NET-WebForms.csproj";
Same as above, can we replace this string literal?

e.g. `WebFormsProjectPath => Path.Combine(_targetDir, _webFormsDir, "ASP.NET-WebForms", "WebForms.csproj");`

2021-11-09 17:44 UTC, Eruanion approved these changes

2021-11-09 19:10 UTC, kanikaul-amazon reviewed
Thanks for the changes, looks good overall. We also need to keep track of adding the feature to our Datastore

2021-11-10 00:55 UTC, kanikaul-amazon approved these changes

2021-11-10 01:34 UTC, jonlouie approved these changes

2021-11-10 05:18 UTC, merged