Modified in-place porting to be done internally
aws/cta pull request #447
Opened 2021-12-08 22:46 UTC by comsemer

## Description
* WebForms2Blazor now does in-place porting inside MigrationManager
* Added functions for deleting files and directories
* Added use of new file management functions
* Added new tests for file management functions

---
*By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.*

2021-12-08 23:01 UTC, jonlouie approved these changes

2021-12-08 23:43 UTC, saikiranakula-amzn requested changes

2021-12-08 23:43 UTC, saikiranakula-amzn commented on src/CTA.Rules.Update/CodeReplacer.cs
> +                MigrationManager migrationManager = new MigrationManager(projectDir, "", _analyzerResult, _projectConfiguration, _projectResult);
add the solution path

2021-12-09 00:10 UTC, saikiranakula-amzn approved these changes

2021-12-09 00:24 UTC, jonlouie approved these changes

2021-12-09 00:26 UTC, merged